version: '3.9'
services:
  catalog_backend:
    build:
      context: ./catalog-backend
    image: nezyap/catalog-backend
    ports:
      - 3331:3331
    restart: unless-stopped
    container_name: catalog-backend

  payment_backend:
    build:
      context: ./payment-backend
    image: nezyap/payment-backend
    ports:
      - 3332:3332
    restart: unless-stopped
    container_name: payment-backend
    environment:
      - CATALOG_BACKEND_URL=http://catalog_backend:3331
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    links:
      - 'redis'
      - 'catalog_backend'

  catalog_frontend:
    build:
      context: ./catalog-frontend
    image: nezyap/catalog-frontend
    ports:
      - 2221:2221
    restart: unless-stopped
    container_name: catalog-frontend
    environment:
      - PORT=2221
      - REACT_APP_CATALOG_BACKEND_URL=http://localhost:3331
      - REACT_APP_PAYMENT_FRONTEND_BASE_URL=http://localhost:2222

  payment_frontend:
    build:
      context: ./payment-frontend
    image: nezyap/payment-frontend
    ports:
      - 2222:2222
    restart: unless-stopped
    container_name: payment-frontend
    environment:
      - PORT=2222
      - REACT_APP_PAYMENT_BACKEND_URL=http://localhost:3332
      - REACT_APP_CATALOG_FRONTEND_BASE_URL=http://localhost:2221
      - REACT_APP_CATALOG_BACKEND_BASE_URL=http://localhost:3331

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: unless-stopped
    container_name: redis
    volumes:
      - /tmp/redis/data:/data
