apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nezyap.fullname" . }}-ingress
  labels:
    {{- include "nezyap.labels" . | nindent 4 }}
    app.kubernetes.io/element: ingress
  annotations:
    {{- if .Values.ingress.usePrefix }}
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{- else }}
    k8s-addon: ingress-nginx.addons.k8s.io
    {{- end }}
spec:
  rules:
  {{- if .Values.ingress.usePrefix }}
  - http:
      paths:
      - backend:
          service:
            name: {{ include "nezyap.fullname" . }}-payment-frontend-svc
            port:
              name: http
        path: {{ .Values.payment.frontend.ingress.prefix }}
        pathType: Prefix
  {{- else }}
  - host: "{{ .Values.payment.frontend.ingress.host }}"
    http:
      paths:
      - backend:
          service:
            name: {{ include "nezyap.fullname" . }}-payment-frontend-svc
            port:
              name: http
        path: /
        pathType: Prefix
  {{- end }}

  {{- if .Values.ingress.usePrefix }}
  - http:
      paths:
      - backend:
          service:
            name: {{ include "nezyap.fullname" . }}-payment-backend-svc
            port:
              name: http
        path: {{ .Values.payment.backend.ingress.prefix }}
        pathType: Prefix
  {{- else }}
  - host: "{{ .Values.payment.backend.ingress.host }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "nezyap.fullname" . }}-payment-backend-svc
            port:
              name: http
  {{- end }}

  {{- if .Values.ingress.usePrefix }}
  - http:
      paths:
      - backend:
          service:
            name: {{ include "nezyap.fullname" . }}-catalog-frontend-svc
            port:
              name: http
        path: {{ .Values.catalog.frontend.ingress.prefix }}
        pathType: Prefix
  {{- else }}
  - host: "{{ .Values.catalog.frontend.ingress.host }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "nezyap.fullname" . }}-catalog-frontend-svc
            port:
              name: http
  {{- end }}

  {{- if .Values.ingress.usePrefix }}
  - http:
      paths:
      - backend:
          service:
            name: {{ include "nezyap.fullname" . }}-catalog-backend-svc
            port:
              name: http
        path: {{ .Values.catalog.backend.ingress.prefix }}
        pathType: Prefix
  {{- else }}
  - host: "{{ .Values.catalog.backend.ingress.host }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "nezyap.fullname" . }}-catalog-backend-svc
            port:
              name: http
  {{- end }}