apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ include "nezyap.fullname" . }}-payment-frontend
  namespace: {{ include "nezyap.name" . }}
  labels:
    {{- include "nezyap.labels" . | nindent 4 }}
    app.kubernetes.io/element: payment-frontend
spec:
  triggers:
  - type: GitHub
    github:
      secretReference:
        name: {{ include "nezyap.fullname" . }}-nicolas-cunin-lyra-github-secret
  source:
      type: "Git"
      git:
        uri: {{ .Values.source.repository }}
        ref: {{ .Values.source.branch }}
      contextDir: payment-frontend
  strategy:
    type: Source
    sourceStrategy:
        from:
          kind: ImageStreamTag
          namespace: openshift
          name: nodejs:14-ubi8
        incremental: true
  output:
    to:
      kind: ImageStreamTag
      name: {{ include "nezyap.fullname" . }}-payment-frontend:{{ .Values.image.version }}
      namespace: {{ include "nezyap.name" . }}
