apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nezyap.fullname" . }}-payment-frontend-deploy
  labels:
    {{- include "nezyap.labels" . | nindent 4 }}
    app.kubernetes.io/element: payment-frontend-deploy
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nezyap.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/element: payment-frontend
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nezyap.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/element: payment-frontend
    spec:
      serviceAccountName: {{ include "nezyap.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ include "nezyap.fullname" . }}-payment-frontend
        image: {{ .Values.image.registry }}/nezyap/payment-frontend:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.payment.frontend.port }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: {{ include "nezyap.fullname" . }}-payment-frontend-cm
              key: PORT
        - name: REACT_APP_PAYMENT_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "nezyap.fullname" . }}-payment-frontend-cm
              key: PAYMENT_BACKEND_URL
        - name: REACT_APP_CATALOG_FRONTEND_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "nezyap.fullname" . }}-payment-frontend-cm
              key: CATALOG_FRONTEND_BASE_URL
        - name: REACT_APP_CATALOG_BACKEND_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "nezyap.fullname" . }}-payment-frontend-cm
              key: CATALOG_BACKEND_BASE_URL
        livenessProbe:
          httpGet:
            path: /transactions
            port: {{ .Values.payment.frontend.port }}
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /transactions
            port: {{ .Values.payment.frontend.port }}
          initialDelaySeconds: 2
          periodSeconds: 5
          failureThreshold: 30
        
