apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nezyap.fullname" . }}-payment-frontend-ingress
  labels:
    {{- include "nezyap.labels" . | nindent 4 }}
    app.kubernetes.io/element: payment-frontend-ingress
spec:
  rules:
  - host: "{{ .Values.payment.frontend.ingress.host }}"
    http:
      paths:
      - backend:
          service:
            name: {{ include "nezyap.fullname" . }}-payment-frontend-svc
            port:
              name: http
        path: /
        pathType: Prefix