apiVersion: v1
kind: Service
metadata:
  name: {{ include "nezyap.fullname" . }}-payment-frontend-svc
  labels:
    {{- include "nezyap.labels" . | nindent 4 }}
    app.kubernetes.io/element: payment-frontend-svc
spec:
  type: ClusterIP
  selector:
    {{- include "nezyap.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/element: payment-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ .Values.payment.frontend.port }}
