apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nezyap.fullname" . }}-redis-cm
  namespace: {{ include "nezyap.name" . }}
data:
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru