apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nezyap.fullname" . }}-redis-deploy
  namespace: {{ include "nezyap.name" . }}
  labels:
    {{- include "nezyap.labels" . | nindent 4 }}
    app.kubernetes.io/element: redis-deploy
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nezyap.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/element: redis
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nezyap.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/element: redis
    spec:
      serviceAccountName: {{ include "nezyap.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ include "nezyap.fullname" . }}-redis
        image: redis:5.0.4
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - redis-server
        - "/redis-master/redis.conf"
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: {{ .Values.redis.port }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        resources:
          {{- toYaml .Values.redis.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master
          name: config
      volumes:
      - name: data
        emptyDir: {}
      - name: config
        configMap:
          name: {{ include "nezyap.fullname" . }}-redis-cm
          items:
          - key: redis-config
            path: redis.conf
