apiVersion: v1
kind: Service
metadata:
  name:  {{ include "nezyap.fullname" . }}-redis-svc
  namespace: {{ include "nezyap.name" . }}
  labels:
    {{- include "nezyap.labels" . | nindent 4 }}
    app.kubernetes.io/element: redis-svc
spec:
  type: ClusterIP
  selector:
    {{- include "nezyap.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/element: redis
  ports:
    - protocol: TCP
      port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
