apiVersion: v1
kind: DeploymentConfig
metadata:
  name: {{ include "nezyap.fullname" . }}-catalog-backend
  labels:
    {{- include "nezyap.labels" . | nindent 4 }}
    app.kubernetes.io/element: catalog-backend
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nezyap.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/element: catalog-backend
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nezyap.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/element: catalog-backend
    spec:
      serviceAccountName: {{ include "nezyap.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ include "nezyap.fullname" . }}-catalog-backend
        image: {{ .Values.image.registry }}/nezyap/catalog-backend:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.catalog.backend.port }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.catalog.backend.port }}
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.catalog.backend.port }}
          initialDelaySeconds: 2
          periodSeconds: 5
  triggers:
  - type: ConfigChange 
  - imageChangeParams:
      automatic: true
      containerNames:
      - {{ include "nezyap.fullname" . }}-catalog-backend
      from:
        kind: ImageStreamTag
        name: {{ .Values.image.registry }}/nezyap/catalog-backend:{{ .Values.image.version }}
  strategy:
    type: Rolling
