apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ include "nezyap.fullname" . }}-catalog-frontend
  labels:
    {{- include "nezyap.labels" . | nindent 4 }}
    app.kubernetes.io/element: catalog-frontend
spec:
  triggers:
  - type: GitHub
    github:
      secretReference:
        name: {{ include "nezyap.fullname" . }}-nicolas-cunin-lyra-github-secret
  source:
      type: "Git"
      git:
        uri: https://github.com/nicolas-cunin-lyra/nezyap#feature/s2i
      contextDir: catalog-frontend
  strategy:
    type: Source
    sourceStrategy:
        from:
          kind: ImageStreamTag
          namespace: openshift
          name: nodejs:latest
        incremental: true
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.image.registry }}/nezyap/catalog-frontend:{{ .Values.image.version }}
