apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-frontend-cm
data:
  PORT: {{ .Values.catalog.frontend.port }}
  CATALOG_BACKEND_URL: "http://{{ .Values.catalog.backend.ingress.host }}"
  PAYMENT_FRONTEND_BASE_URL: "http://{{ .Values.payment.frontend.ingress.host }}"
