apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nezyap.fullname" . }}-catalog-frontend-cm
  namespace: {{ include "nezyap.name" . }}
data:
  PORT: "{{ .Values.catalog.frontend.port }}"
  CATALOG_BACKEND_URL: "http://{{ .Values.catalog.backend.ingress.host }}{{ .Values.catalog.backend.ingress.prefix }}"
  PAYMENT_FRONTEND_BASE_URL: "http://{{ .Values.payment.frontend.ingress.host }}{{ .Values.payment.frontend.ingress.prefix }}"
