apiVersion: v1
kind: Service
metadata:
  name: {{ include "nezyap.fullname" . }}-catalog-backend-svc
  labels:
    {{- include "nezyap.labels" . | nindent 4 }}
    app.kubernetes.io/element: catalog-frontend-svc
spec:
  type: ClusterIP
  selector:
    {{- include "nezyap.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/element: catalog-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.catalog.frontend.port }}
      targetPort: {{ .Values.catalog.frontend.port }}