apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nezyap.fullname" . }}-payment-backend-cm
  namespace: {{ include "nezyap.name" . }}
data:
  CATALOG_BACKEND_URL: "http://{{ include "nezyap.fullname" . }}-catalog-backend-svc"
  REDIS_HOST: "{{ include "nezyap.fullname" . }}-redis-svc"
  REDIS_PORT: "{{ .Values.redis.port }}"
