apiVersion: v1
kind: Service
metadata:
  name: {{ include "nezyap.fullname" . }}-payment-backend-svc
  labels:
    {{- include "nezyap.labels" . | nindent 4 }}
    app.kubernetes.io/element: payment-backend-svc
spec:
  type: ClusterIP
  selector:
    {{- include "nezyap.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/element: payment-backend
  ports:
    - protocol: TCP
      port: {{ .Values.payment.backend.port }}
      targetPort: {{ .Values.payment.backend.port }}